name: coffee_shop
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.3
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.5
  meta: ^1.11.0
  talker: ^4.1.3
  talker_dio_logger: ^4.1.3
  talker_flutter: ^4.1.3
  talker_bloc_logger: ^4.1.3
  bloc: ^8.1.4
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
